<?php

/**
 * @file
 * An installation file for OpenLocal Core.
 */

/**
 * Implementation of hook_install()
 */
function openlocal_core_install() {
  variable_set('image_resize_filter_threshold', 1000);

  // Change some general Panopoly settings.
  variable_set('panopoly_core_breadcrumb_title', 0);
  variable_set('panopoly_magic_pane_add_preview', 2);
  variable_set('panopoly_admin_advanced_plugins', 1);
}
