<?php
/**
 * @file
 * openlocal_issue.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function openlocal_issue_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-ol_issue-field_ol_details'
  $field_instances['node-ol_issue-field_ol_details'] = array(
    'bundle' => 'ol_issue',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Describe the issue, giving as much revelant information as possible.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ol_details',
    'label' => 'Details',
    'required' => 0,
    'settings' => array(
      'linkit' => array(
        'button_text' => 'Search',
        'enable' => 0,
        'profile' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-ol_issue-field_ol_issue_status'
  $field_instances['node-ol_issue-field_ol_issue_status'] = array(
    'bundle' => 'ol_issue',
    'default_value' => array(
      0 => array(
        'value' => 'open',
      ),
    ),
    'deleted' => 0,
    'description' => 'Leave this as Open when creating a new issue. Site managers may set it to "Need more information" if they have questions. Set it to "Closed" if your issue has been resolved.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ol_issue_status',
    'label' => 'Status',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-ol_issue-field_ol_issue_type'
  $field_instances['node-ol_issue-field_ol_issue_type'] = array(
    'bundle' => 'ol_issue',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Choose what type of issue this relates to.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ol_issue_type',
    'label' => 'Type',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Choose what type of issue this relates to.');
  t('Describe the issue, giving as much revelant information as possible.');
  t('Details');
  t('Leave this as Open when creating a new issue. Site managers may set it to "Need more information" if they have questions. Set it to "Closed" if your issue has been resolved.');
  t('Status');
  t('Type');

  return $field_instances;
}
